operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 5
  - op_name: "按键-特殊攻击-按下"
  - op_name: "等待秒数"
    seconds: 0.5
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 35
  - op_name: "等待秒数"
    seconds: 1