# 根据动画实测，动画持续2秒
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1.5
  - op_name: "按键-普通攻击-按下"
  - op_name: "等待秒数"
    seconds: 0.5
  - op_name: "按键-普通攻击-松开"
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 25