operations:
  - op_name: "设置状态"
    state: "自定义-苍角-展旗"
  - op_name: "设置状态"
    state: "自定义-不使用快速支援"
    seconds: 10
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 12
  - op_name: "按键-特殊攻击"
    way: "松开"
  - op_name: "等待秒数"
    seconds: 0.1

  - op_name: "按键-特殊攻击"
    way: "按下"
    post_delay: 1.8

  - operation_template: "苍角-闪2A合轴"