# 根据动画实测，动画持续2.5秒
operations:
  - operation_template: "通用-闪避-左"
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1.2
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 11
  - op_name: "清除状态"
    state: "自定义-不使用快速支援"
  - op_name: "按键-切换角色-下一个"