# 根据动画实测，动画持续2秒
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2
  - op_name: "设置状态"
    state: "自定义-零号安比-白雷"
    add: -330
  - op_name: "按键-特殊攻击"
    post_delay: 0.25
    repeat: 2
  - op_name: "设置状态"
    state: "自定义-零号安比-白雷"
    add: -330
  - op_name: "按键-特殊攻击"
    post_delay: 0.25
    repeat: 2
  - op_name: "清除状态"
    state: "自定义-零号安比-白雷"
  - op_name: "按键-特殊攻击"
    post_delay: 0.25
    repeat: 3
  - op_name: "等待秒数"
    seconds: 0.2
