idx: 2
op_list:
- data:
  - '1578'
  - '898'
  op_type: move
- data:
  - '1538'
  - '899'
  op_type: move
- data:
  - '1501'
  - '899'
  op_type: move
- data:
  - '1451'
  - '836'
  op_type: move
- data:
  - '1480'
  - '906'
  op_type: move
- data:
  - '1405'
  - '826'
  op_type: move
- data:
  - '1407'
  - '807'
  op_type: move
- data:
  - '1330'
  - '806'
  op_type: move
- data:
  - '1285'
  - '770'
  op_type: move
- data:
  - '1233'
  - '739'
  op_type: move
- data:
  - '1173'
  - '753'
  op_type: move
tp_area_id: former_employee_community
tp_name: 旧商业楼
