idx: 4
op_list:
- data:
  - '1240'
  - '1169'
  op_type: move
- data:
  - '1151'
  - '1165'
  op_type: move
- data:
  - '1149'
  - '1230'
  op_type: move
- data:
  - '1090'
  - '1220'
  op_type: move
- data:
  - '1087'
  - '1260'
  op_type: move
- data:
  - '1032'
  - '1234'
  op_type: move
- data:
  - '1020'
  - '1179'
  op_type: move
- data:
  - '1015'
  - '1126'
  op_type: move
- data:
  - '964'
  - '1112'
  op_type: move
- data:
  - '943'
  - '1063'
  op_type: move
- data:
  - '940'
  - '1015'
  op_type: move
- data:
  - '959'
  - '986'
  op_type: move
tp_area_id: former_employee_community
tp_name: 中央广场
