idx: 5
op_list:
- data:
  - '677'
  - '873'
  op_type: move
- data:
  - '694'
  - '835'
  op_type: move
- data:
  - '708'
  - '908'
  op_type: move
- data:
  - '784'
  - '918'
  op_type: move
- data:
  - '810'
  - '919'
  op_type: move
- data:
  - '953'
  - '944'
  op_type: move
- data:
  - '959'
  - '986'
  op_type: move
- data:
  - '940'
  - '1015'
  op_type: move
- data:
  - '943'
  - '1063'
  op_type: move
- data:
  - '964'
  - '1112'
  op_type: move
- data:
  - '1022'
  - '1116'
  op_type: move
- data:
  - '1025'
  - '1148'
  op_type: move
- data:
  - '1020'
  - '1179'
  op_type: move
- data:
  - '1032'
  - '1234'
  op_type: move
- data:
  - '1087'
  - '1260'
  op_type: move
tp_area_id: former_employee_community
tp_name: 西侧广场
