idx: 5
op_list:
- data:
  - '665'
  - '857'
  op_type: move
- data:
  - '712'
  - '863'
  op_type: move
- data:
  - '768'
  - '864'
  op_type: move
- data:
  - '775'
  - '889'
  op_type: move
- data:
  - '768'
  - '919'
  op_type: move
- data:
  - '810'
  - '917'
  op_type: move
- data:
  - '870'
  - '940'
  op_type: move
- data:
  - '953'
  - '940'
  op_type: move
- data:
  - '959'
  - '986'
  op_type: move
- data:
  - '940'
  - '1015'
  op_type: move
- data:
  - '943'
  - '1063'
  op_type: move
- data:
  - '964'
  - '1112'
  op_type: move
- data:
  - '1022'
  - '1116'
  op_type: move
- data:
  - '1025'
  - '1148'
  op_type: move
- data:
  - '1020'
  - '1179'
  op_type: move
- data:
  - '1032'
  - '1234'
  op_type: move
- data:
  - '1087'
  - '1260'
  op_type: move
tp_area_id: former_employee_community
tp_name: 西侧广场
