template_name: "速切模板-雅"
handlers:
  - states: "[前台-雅]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-雅]"
    sub_handlers:
      # 这里代表了异常角色出场，要清空其他异常积累的累计
      # 比如雅是烈霜异常，所以要清空火冰物电，一般只有异常角色需要清空
      - states: "[自定义-异常-物理, 0, 99] | [自定义-异常-冰, 0, 99] | [自定义-异常-火, 0, 99] | [自定义-异常-电, 0, 99]"
        debug_name: "清除其他异常积蓄"
        operations:
          - op_name: "清除状态"
            state_list:
              [
                "自定义-异常-火",
                "自定义-异常-冰",
                "自定义-异常-物理",
                "自定义-异常-电",
              ]

      # 黄光入场也要清除角色状态
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "雅-支援攻击"

      # 红光
      - states: "[自定义-红光闪避, 0, 1]"
        operations:
          - operation_template: "雅-闪A"

      # 连携
      - states: "[自定义-连携换人, 0, 0.5]"
        operations:
          - operation_template: "雅-连携攻击"

      # 初始状态
      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[按键可用-快速支援, 0, 0.5]"
            operations:
              - op_name: "等待秒数"
                seconds: 1.0
          - states: ""
            operations:
              - op_name: "等待秒数"
                seconds: 0.3

      - states: "[自定义-星见雅-蓄力中, -5, 0]"
        debug_name: "合轴"
        operations:
          - op_name: "设置状态"
            state: "自定义-速切结束"

      - states: "[雅-落霜]{6, 6}"
        interrupt_states: "[雅-落霜]{0, 0}"
        debug_name: "拔刀"
        operations:
          - operation_template: "雅-拔刀斩"
          - op_name: "等待秒数"
            seconds: 4.2
          - op_name: "按键-普通攻击-松开"

      - states: "[雅-落霜]{0, 5}"
        interrupt_states: "[雅-落霜]{6, 6}"
        sub_handlers:

        - states: "[雅-终结技可用] & [雅-落霜]{0, 3}"
          operations:
            - operation_template: "雅-终结技"

        - states: "[雅-特殊技可用] & [雅-落霜, 0, 999]{0, 2} & [雅-能量]{80, 120}"
          debug_name: "强化特殊技二连"
          operations:
            - operation_template: "雅-特殊攻击二连"

        - states: "[雅-特殊技可用] & [雅-落霜, 0, 999]{0, 5}"
          debug_name: "强化特殊技"
          operations:
            - operation_template: "雅-特殊攻击"

        - states: ""
          debug_name: "普通攻击"
          operations:
            - operation_template: "雅-普通攻击"
