template_name: "速切模板-苍角"
handlers:
  - states: "[前台-苍角]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-苍角]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "苍角-支援攻击"

      - states: "[自定义-红光闪避, 0, 1]"
        operations:
          - operation_template: "通用-闪A"

      - states: "[自定义-连携换人, 0, 0.5]"
        operations:
          - operation_template: "苍角-连携攻击"

      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[按键可用-快速支援, 0, 0.5]"
            sub_handlers:
            - states: "[苍角-终结技可用] & ![自定义-连携换人, 0, 10] & [苍角-涡流, 0, 30]{0, 1}"
              operations:
                - op_name: "设置状态"
                  state: "自定义-不使用快速支援"
                  seconds: 10
                - operation_template: "苍角-终结技"
                - operation_template: "苍角-闪2A合轴"
            - states: ""
              operations:
                - op_name: "等待秒数"
                  seconds: 1.1
          - states: ""
            operations:
              - op_name: "等待秒数"
                seconds: 0.3

      - states: "[苍角-终结技可用] & ![自定义-连携换人, 0, 10] & [苍角-涡流, 0, 30]{0, 1} & ![自定义-苍角-展旗, 0, 5]"
        debug_name: "放大招咯"
        operations:
          - op_name: "设置状态"
            state_list: ["自定义-不使用快速支援", "自定义-无视闪光", "自定义-动作不打断"]
            seconds: 10
          - operation_template: "苍角-终结技"
          - operation_template: "苍角-闪2A合轴"

      - states: "[自定义-苍角-展旗,0,5] & [按键可用-快速支援,0,1] | ([自定义-苍角-展旗, 5, 30] & ![苍角-特殊技可用])"
        debug_name: "触发快速支援或者没特殊技可用"
        operations:
          - operation_template: "苍角-闪2A合轴"

      - states: "[自定义-苍角-展旗, 0, 3]"
        debug_name: "展旗开始"
        interrupt_states: "[按键可用-快速支援,0,1]"
        operations:
          - op_name: "按键-特殊攻击-按下"
          - op_name: "等待秒数"
            seconds: 3

      - states: "[苍角-特殊技可用] & ![自定义-苍角-展旗, 0, 1]"
        debug_name: "扇风开始"
        interrupt_states: "[自定义-苍角-展旗, 0.1, 30] & ([苍角-涡流, 0, 30]{2, 3} | [苍角-能量]{0,30})"
        operations:
          - op_name: "设置状态"
            state_list: ["自定义-苍角-展旗"]
          - op_name: "设置状态"
            state_list: ["自定义-不使用快速支援", "自定义-无视闪光", "自定义-动作不打断"]
            seconds: 7
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
            repeat: 50

      - states: ""
        debug_name: "上个buff先"
        operations:
          - op_name: "设置状态"
            state_list: ["自定义-不使用快速支援", "自定义-无视闪光", "自定义-动作不打断"]
            seconds: 7
          - operation_template: "苍角-1E展旗合轴"