check_dodge_interval: 0.02  # 闪避识别间隔
check_agent_interval: 0.1  # 代理人识别间隔
auto_lock_interval: 0  # 关闭自动锁定
auto_turn_interval: 0  # 关闭自动转向

scenes:
  - triggers: ["闪避识别-黄光"]
    interval: 0.5
    handlers:
      - states: ""
        sub_handlers:
        - state_template: "支援攻击模板-特殊情况"  # 特殊情况
        - state_template: "支援攻击模板-击破"  # 格挡攻击优先击破可以快速打进失衡
        - state_template: "支援攻击模板-命破"  # 命破好像也不错
        - state_template: "支援攻击模板-防护"  # 防护一般格挡性能优越
        - state_template: "支援攻击模板-异常"  # 异常一般格挡上异常效率也不错
        - state_template: "支援攻击模板-下一个"  # 剩下的都不优秀了
  - triggers: ["闪避识别-红光", "闪避识别-声音"]
    interval: 0.5
    handlers:
      - states: ""
        sub_handlers:
          # 一般情况下里面都是直接设置红光闪避状态，不要在里面写闪A动作，因为同一个触发器无法打断本触发器，可能导致闪A中无法闪A
          - state_template: "闪A模板-全角色"
  - triggers: []
    priority: 9
    interval: 0.02
    handlers:
      # 主线程默认情况会走到这里
      - states: "[自定义-黄光切人, 0, 0.5] | [自定义-红光切人, 0, 0.5]"
        sub_handlers:
          # 这个代表，每个角色的动作做完之后，不进行合轴，也根据特殊情况进行切人，防止循环打乱
          - state_template: "速切模板-全角色"
