list_type: whitelist
name: 职工社区旧址
route_items:
- former_employee_community_1
- former_employee_community_2
- former_employee_community_3
- former_employee_community_4
- former_employee_community_5
- former_employee_community_6
