idx: 1
op_list:
- data:
  - '385'
  - '1092'
  op_type: move
- data:
  - '386'
  - '1123'
  op_type: move
- data:
  - '480'
  - '1111'
  op_type: move
- data:
  - '526'
  - '1097'
  op_type: move
- data:
  - '595'
  - '1045'
  op_type: move
- data:
  - '595'
  - '969'
  op_type: move
- data:
  - '595'
  - '950'
  op_type: move
tp_area_id: former_research_center
tp_name: 科研院西侧
