idx: 2
op_list:
- data:
  - '747'
  - '457'
  op_type: move
- data:
  - '751'
  - '360'
  op_type: move
- data:
  - '744'
  - '309'
  op_type: move
- data:
  - '757'
  - '262'
  op_type: move
- data:
  - '732'
  - '230'
  op_type: move
- data:
  - '688'
  - '248'
  op_type: move
- data:
  - '633'
  - '246'
  op_type: move
- data:
  - '567'
  - '280'
  op_type: move
- data:
  - '568'
  - '323'
  op_type: move
tp_area_id: former_research_center
tp_name: 科研院内
