idx: 3
op_list:
- data:
  - '987'
  - '1008'
  op_type: move
- data:
  - '946'
  - '1056'
  op_type: move
- data:
  - '978'
  - '1073'
  op_type: move
- data:
  - '960'
  - '987'
  op_type: move
- data:
  - '962'
  - '923'
  op_type: move
- data:
  - '975'
  - '826'
  op_type: move
- data:
  - '972'
  - '757'
  op_type: move
- data:
  - '976'
  - '736'
  op_type: move
- data:
  - '965'
  - '661'
  op_type: move
- data:
  - '947'
  - '638'
  op_type: move
- data:
  - '930'
  - '621'
  op_type: move
tp_area_id: former_research_center
tp_name: 二楼平台
